services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: transformix-web
    container_name: transformix-web
    restart: unless-stopped
    ports:
      - "3050:3000"
    environment:
      - NODE_ENV=production
